#!/bin/sh

licensecheck --check '.*' --recursive --copyright --deb-machine --ignore '^flatted\.jpg|test/circular\.txt|(debian/(changelog|copyright(_hints)?))$' --lines 0 -- * > debian/copyright_hints
